if ( ! ${?PATH} ) setenv PATH ""
setenv PATH "/home/dfl1826a/Github/TPs/L3/PFITA/_pfita/opamroot/system/bin:$PATH"
if ( ! ${?OCAML_TOPLEVEL_PATH} ) setenv OCAML_TOPLEVEL_PATH ""
setenv OCAML_TOPLEVEL_PATH "/home/dfl1826a/Github/TPs/L3/PFITA/_pfita/opamroot/system/lib/toplevel"
if ( ! ${?PERL5LIB} ) setenv PERL5LIB ""
setenv PERL5LIB "/home/dfl1826a/Github/TPs/L3/PFITA/_pfita/opamroot/system/lib/perl5:$PERL5LIB"
if ( ! ${?MANPATH} ) setenv MANPATH ""
setenv MANPATH "${MANPATH}:/home/dfl1826a/Github/TPs/L3/PFITA/_pfita/opamroot/system/man"
if ( ! ${?CAML_LD_LIBRARY_PATH} ) setenv CAML_LD_LIBRARY_PATH ""
setenv CAML_LD_LIBRARY_PATH "/home/dfl1826a/Github/TPs/L3/PFITA/_pfita/opamroot/system/lib/stublibs:/usr/lib64/ocaml/stublibs"
